### PR TITLE
README: Mention corfu-doc-terminal

### PR DESCRIPTION
**Pull request by jgarte**

### CODE REVIEW

**Comment by minad** [comment]
This can be mentioned later. The situation around corfu-doc is in flux.

**Comment by jgarte** [comment]
> This can be mentioned later. The situation around corfu-doc is in flux.

Where can I read about the flux?

@minad Do you use `corfu-doc`?

 I have stopped using it because I realized that I prefer to just jump to the definition or get any info in the minibuffer.

**Comment by minad** [comment]
See #178. We plan to add corfu-doc here soon. Then corfu-terminal will include support directly and corfu-doc-terminal won't be needed.

**Comment by jgarte** [comment]
Sounds great

**Pull request closed without merging**
